query fetchOrders(
  $offset: Int
  $limit: Int
  $order_by: [orders_order_by!]
  $where: orders_bool_exp
) {
  orders(
    offset: $offset
    limit: $limit
    order_by: $order_by
    where: $where
  ) {
    id
    shipping_full_name
    shipping_phone_number
    is_paid
    status
    code
    created_at
    total_price
    _status {
      name
    }
  }
}